port: 8081
database:
  master:
    ip: localhost
    username: root
    password: 123456
    port: 3306
    base: ecoShop
  slave:
    ip: localhost
    username: root
    password: 123456
    port: 3306
    base: ecoShop2