-- 1. 商品分类表
CREATE TABLE product_category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(100) NOT NULL COMMENT '分类名称',
    code VARCHAR(50) NOT NULL COMMENT '分类编码',
    parent_id BIGINT DEFAULT NULL COMMENT '父分类ID',
    level INT DEFAULT 1 COMMENT '分类级别',
    path VARCHAR(255) DEFAULT NULL COMMENT '分类路径',
    icon VARCHAR(255) DEFAULT NULL COMMENT '分类图标',
    sort INT DEFAULT 0 COMMENT '排序号',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='商品分类表';

-- 2. 品牌表
CREATE TABLE brand (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(100) NOT NULL COMMENT '品牌名称',
    logo VARCHAR(255) DEFAULT NULL COMMENT '品牌logo',
    description VARCHAR(500) DEFAULT NULL COMMENT '品牌描述',
    website VARCHAR(255) DEFAULT NULL COMMENT '品牌官网',
    sort INT DEFAULT 0 COMMENT '排序号',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='品牌表';

-- 3. 规格表
CREATE TABLE specification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(100) NOT NULL COMMENT '规格名称',
    code VARCHAR(50) NOT NULL COMMENT '规格编码',
    category_id BIGINT DEFAULT NULL COMMENT '所属分类ID',
    sort INT DEFAULT 0 COMMENT '排序号',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='规格表';

-- 4. 规格值表
CREATE TABLE specification_value (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    spec_id BIGINT NOT NULL COMMENT '规格ID',
    value VARCHAR(100) NOT NULL COMMENT '规格值',
    sort INT DEFAULT 0 COMMENT '排序号',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='规格值表';

-- 5. 商品表
CREATE TABLE product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(200) NOT NULL COMMENT '商品名称',
    code VARCHAR(50) NOT NULL COMMENT '商品编码',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    brand_id BIGINT DEFAULT NULL COMMENT '品牌ID',
    main_image VARCHAR(255) DEFAULT NULL COMMENT '主图',
    sub_images TEXT DEFAULT NULL COMMENT '子图(JSON格式)',
    detail TEXT DEFAULT NULL COMMENT '商品详情',
    price DECIMAL(10,2) NOT NULL COMMENT '售价',
    market_price DECIMAL(10,2) DEFAULT NULL COMMENT '市场价',
    cost_price DECIMAL(10,2) DEFAULT NULL COMMENT '成本价',
    stock INT DEFAULT 0 COMMENT '库存',
    sales INT DEFAULT 0 COMMENT '销量',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    weight DECIMAL(10,2) DEFAULT NULL COMMENT '重量(kg)',
    status TINYINT DEFAULT 1 COMMENT '状态(1:上架,0:下架)',
    is_new TINYINT DEFAULT 0 COMMENT '是否新品(1:是,0:否)',
    is_hot TINYINT DEFAULT 0 COMMENT '是否热销(1:是,0:否)',
    is_recommend TINYINT DEFAULT 0 COMMENT '是否推荐(1:是,0:否)',
    keywords VARCHAR(200) DEFAULT NULL COMMENT '关键字',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='商品表';

-- 6. 商品SKU表
CREATE TABLE product_sku (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    sku_code VARCHAR(50) NOT NULL COMMENT 'SKU编码',
    spec_values VARCHAR(500) DEFAULT NULL COMMENT '规格值(JSON格式)',
    price DECIMAL(10,2) NOT NULL COMMENT '售价',
    market_price DECIMAL(10,2) DEFAULT NULL COMMENT '市场价',
    cost_price DECIMAL(10,2) DEFAULT NULL COMMENT '成本价',
    stock INT DEFAULT 0 COMMENT '库存',
    sales INT DEFAULT 0 COMMENT '销量',
    image VARCHAR(255) DEFAULT NULL COMMENT 'SKU图片',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='商品SKU表';

-- 7. 商品-规格关联表
CREATE TABLE product_specification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    spec_id BIGINT NOT NULL COMMENT '规格ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='商品与规格关联表';

-- 8. 商品评价表
CREATE TABLE product_review (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    order_id BIGINT NOT NULL COMMENT '订单ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    rating INT DEFAULT 5 COMMENT '评分(1-5)',
    content TEXT DEFAULT NULL COMMENT '评价内容',
    images TEXT DEFAULT NULL COMMENT '评价图片(JSON格式)',
    reply TEXT DEFAULT NULL COMMENT '商家回复',
    reply_time DATETIME DEFAULT NULL COMMENT '回复时间',
    status TINYINT DEFAULT 1 COMMENT '状态(1:显示,0:隐藏)',
    is_anonymous TINYINT DEFAULT 0 COMMENT '是否匿名(1:是,0:否)',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='商品评价表';

-- 9. 库存变动记录表
CREATE TABLE stock_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    sku_id BIGINT DEFAULT NULL COMMENT 'SKU ID',
    before_stock INT NOT NULL COMMENT '变动前库存',
    change_amount INT NOT NULL COMMENT '变动数量',
    after_stock INT NOT NULL COMMENT '变动后库存',
    type VARCHAR(20) NOT NULL COMMENT '变动类型(入库/出库/调整)',
    reason VARCHAR(100) DEFAULT NULL COMMENT '变动原因',
    order_id BIGINT DEFAULT NULL COMMENT '关联订单ID',
    operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(50) DEFAULT NULL COMMENT '操作人名称',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='库存变动记录表';

-- 10. 商品收藏表
CREATE TABLE product_favorite (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='商品收藏表'; 