-- ===============================
-- 用户权限模块（ums_）
-- ===============================

-- 1. 中台用户表
CREATE TABLE ums_admin_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    gender CHAR(1) DEFAULT NULL COMMENT '性别(M:男 F:女)',
    avatar VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
    email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    org_id BIGINT DEFAULT NULL COMMENT '所属机构ID',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    last_login_at DATETIME DEFAULT NULL COMMENT '最后登录时间',
    login_ip VARCHAR(50) DEFAULT NULL COMMENT '最后登录IP',
    login_count INT DEFAULT 0 COMMENT '登录次数',
    password_error_count INT DEFAULT 0 COMMENT '密码错误次数',
    locked_until DATETIME DEFAULT NULL COMMENT '锁定截止时间',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='中台用户表';

-- 2. C端用户表
CREATE TABLE ums_customer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
    avatar VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
    gender CHAR(1) DEFAULT NULL COMMENT '性别(M:男 F:女)',
    birthday DATE DEFAULT NULL COMMENT '生日',
    email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    last_login_at DATETIME DEFAULT NULL COMMENT '最后登录时间',
    login_ip VARCHAR(50) DEFAULT NULL COMMENT '最后登录IP',
    register_source VARCHAR(20) DEFAULT NULL COMMENT '注册来源',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='C端用户表';

-- 3. 机构表
CREATE TABLE ums_org (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(100) NOT NULL COMMENT '机构名称',
    code VARCHAR(50) NOT NULL COMMENT '机构编码',
    type VARCHAR(20) DEFAULT '公司' COMMENT '机构类型（集团/分公司/部门）',
    parent_id BIGINT DEFAULT NULL COMMENT '上级机构ID',
    leader VARCHAR(50) DEFAULT NULL COMMENT '负责人',
    phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    email VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    address VARCHAR(200) DEFAULT NULL COMMENT '机构地址',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    sort INT DEFAULT 0 COMMENT '排序号',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='机构表';

-- 4. 岗位表
CREATE TABLE ums_post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(50) NOT NULL COMMENT '岗位名称',
    code VARCHAR(50) NOT NULL COMMENT '岗位编码',
    sort INT DEFAULT 0 COMMENT '显示顺序',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='岗位表';

-- 5. 中台用户-岗位关联表
CREATE TABLE ums_admin_user_post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    post_id BIGINT NOT NULL COMMENT '岗位ID',
    assigned_by VARCHAR(50) DEFAULT NULL COMMENT '分配人',
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '分配时间',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='中台用户与岗位关联表';

-- 6. 角色表
CREATE TABLE ums_role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(50) NOT NULL COMMENT '角色名称',
    code VARCHAR(50) NOT NULL COMMENT '角色编码',
    data_scope VARCHAR(50) DEFAULT '本机构' COMMENT '数据权限范围（全部/本机构/自定义）',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    is_admin TINYINT DEFAULT 0 COMMENT '是否超级管理员(1:是,0:否)',
    sort INT DEFAULT 0 COMMENT '排序号',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='角色表';

-- 7. 中台用户-角色关联表
CREATE TABLE ums_admin_user_role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    assigned_by VARCHAR(50) DEFAULT NULL COMMENT '分配人',
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '分配时间',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='中台用户与角色关联表';

-- 8. 权限表
CREATE TABLE ums_permission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL COMMENT '权限名称',
    code VARCHAR(100) NOT NULL COMMENT '权限编码',
    type VARCHAR(20) DEFAULT '功能' COMMENT '权限类型(菜单/按钮/接口/数据)',
    description VARCHAR(200) DEFAULT NULL COMMENT '权限描述',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    sort INT DEFAULT 0 COMMENT '排序号',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='权限表';

-- 9. 角色-权限关联表
CREATE TABLE ums_role_permission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='角色与权限关联表';

-- 10. 路由表
CREATE TABLE ums_route (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    path VARCHAR(200) NOT NULL COMMENT '路由路径',
    name VARCHAR(100) NOT NULL COMMENT '路由名称',
    component VARCHAR(200) DEFAULT NULL COMMENT '前端组件',
    parent_id BIGINT DEFAULT NULL COMMENT '父级路由ID',
    icon VARCHAR(100) DEFAULT NULL COMMENT '菜单图标',
    order_num INT DEFAULT 0 COMMENT '排序号',
    is_menu TINYINT DEFAULT 1 COMMENT '是否菜单(1:是,0:否)',
    visible TINYINT DEFAULT 1 COMMENT '是否可见(1:可见,0:隐藏)',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    keep_alive TINYINT DEFAULT 1 COMMENT '是否缓存(1:是,0:否)',
    external_link VARCHAR(255) DEFAULT NULL COMMENT '外链地址',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='路由表';

-- 11. 路由-权限关联表
CREATE TABLE ums_route_permission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    route_id BIGINT NOT NULL COMMENT '路由ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='路由与权限关联表'; 