-- 1. 租户表
CREATE TABLE tenant (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL COMMENT '租户名称',
    code VARCHAR(50) NOT NULL COMMENT '租户编码',
    contact VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    email VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    address VARCHAR(200) DEFAULT NULL COMMENT '地址',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    expire_time DATETIME DEFAULT NULL COMMENT '到期时间',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='租户表';

-- 2. 机构表
CREATE TABLE org (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(100) NOT NULL COMMENT '机构名称',
    code VARCHAR(50) NOT NULL COMMENT '机构编码',
    type VARCHAR(20) DEFAULT '公司' COMMENT '机构类型（集团/分公司/部门）',
    parent_id BIGINT DEFAULT NULL COMMENT '上级机构ID',
    leader VARCHAR(50) DEFAULT NULL COMMENT '负责人',
    phone VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    email VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    address VARCHAR(200) DEFAULT NULL COMMENT '机构地址',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    sort INT DEFAULT 0 COMMENT '排序号',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='机构表';

-- 3. 岗位表
CREATE TABLE post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(50) NOT NULL COMMENT '岗位名称',
    code VARCHAR(50) NOT NULL COMMENT '岗位编码',
    sort INT DEFAULT 0 COMMENT '显示顺序',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='岗位表';

-- 4. 用户表
CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    gender CHAR(1) DEFAULT NULL COMMENT '性别(M:男 F:女)',
    avatar VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
    email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    phone VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    org_id BIGINT DEFAULT NULL COMMENT '所属机构ID',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    last_login_at DATETIME DEFAULT NULL COMMENT '最后登录时间',
    login_ip VARCHAR(50) DEFAULT NULL COMMENT '最后登录IP',
    login_count INT DEFAULT 0 COMMENT '登录次数',
    password_error_count INT DEFAULT 0 COMMENT '密码错误次数',
    locked_until DATETIME DEFAULT NULL COMMENT '锁定截止时间',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='用户表';

-- 5. 用户-角色关联表
CREATE TABLE user_role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    assigned_by VARCHAR(50) DEFAULT NULL COMMENT '分配人',
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '分配时间',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='用户与角色关联表';

-- 6. 用户-岗位关联表
CREATE TABLE user_post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    post_id BIGINT NOT NULL COMMENT '岗位ID',
    assigned_by VARCHAR(50) DEFAULT NULL COMMENT '分配人',
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '分配时间',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='用户与岗位关联表';

-- 7. 角色表
CREATE TABLE role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    name VARCHAR(50) NOT NULL COMMENT '角色名称',
    code VARCHAR(50) NOT NULL COMMENT '角色编码',
    data_scope VARCHAR(50) DEFAULT '本机构' COMMENT '数据权限范围（全部/本机构/自定义）',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    is_admin TINYINT DEFAULT 0 COMMENT '是否超级管理员(1:是,0:否)',
    sort INT DEFAULT 0 COMMENT '排序号',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='角色表';

-- 8. 角色-机构关联表
CREATE TABLE role_org (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    org_id BIGINT NOT NULL COMMENT '机构ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='角色与机构关联表';

-- 9. 路由表
CREATE TABLE route (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    path VARCHAR(200) NOT NULL COMMENT '路由路径',
    name VARCHAR(100) NOT NULL COMMENT '路由名称',
    component VARCHAR(200) DEFAULT NULL COMMENT '前端组件',
    parent_id BIGINT DEFAULT NULL COMMENT '父级路由ID',
    icon VARCHAR(100) DEFAULT NULL COMMENT '菜单图标',
    order_num INT DEFAULT 0 COMMENT '排序号',
    is_menu TINYINT DEFAULT 1 COMMENT '是否菜单(1:是,0:否)',
    visible TINYINT DEFAULT 1 COMMENT '是否可见(1:可见,0:隐藏)',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    keep_alive TINYINT DEFAULT 1 COMMENT '是否缓存(1:是,0:否)',
    external_link VARCHAR(255) DEFAULT NULL COMMENT '外链地址',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='路由表';

-- 10. 权限表
CREATE TABLE permission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL COMMENT '权限名称',
    code VARCHAR(100) NOT NULL COMMENT '权限编码',
    type VARCHAR(20) DEFAULT '功能' COMMENT '权限类型(菜单/按钮/接口/数据)',
    description VARCHAR(200) DEFAULT NULL COMMENT '权限描述',
    status TINYINT DEFAULT 1 COMMENT '状态(1:启用,0:禁用)',
    sort INT DEFAULT 0 COMMENT '排序号',
    remark VARCHAR(200) DEFAULT NULL COMMENT '备注',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='权限表';

-- 11. 角色-权限关联表
CREATE TABLE role_permission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='角色与权限关联表';

-- 12. 路由-权限关联表
CREATE TABLE route_permission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    route_id BIGINT NOT NULL COMMENT '路由ID',
    permission_id BIGINT NOT NULL COMMENT '权限ID',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='路由与权限关联表';

-- 13. 登录日志表
CREATE TABLE login_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    ip VARCHAR(50) DEFAULT NULL COMMENT '登录IP',
    user_agent VARCHAR(255) DEFAULT NULL COMMENT 'User-Agent',
    status TINYINT DEFAULT 1 COMMENT '登录状态(1:成功,0:失败)',
    msg VARCHAR(200) DEFAULT NULL COMMENT '登录信息',
    login_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='登录日志表';

-- 14. 操作日志表
CREATE TABLE operate_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
    module VARCHAR(100) DEFAULT NULL COMMENT '操作模块',
    business_type VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
    method VARCHAR(100) DEFAULT NULL COMMENT '方法名',
    request_url VARCHAR(255) DEFAULT NULL COMMENT '请求URL',
    request_method VARCHAR(10) DEFAULT NULL COMMENT '请求方式',
    request_param TEXT DEFAULT NULL COMMENT '请求参数',
    response_data TEXT DEFAULT NULL COMMENT '响应数据',
    ip VARCHAR(50) DEFAULT NULL COMMENT '操作IP',
    status TINYINT DEFAULT 1 COMMENT '操作状态(1:成功,0:失败)',
    error_msg VARCHAR(200) DEFAULT NULL COMMENT '错误消息',
    operate_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    version INT DEFAULT 1 COMMENT '版本号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT='操作日志表'; 